addons:
  sauce_connect: true

sudo: false
language: node_js
language: java

node_js:
  - "6.9.2"
jdk:
  - oraclejdk8

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start

install:
  - npm i

script:
  - npm test
  - npm run coverage
  - npm run client-coverage
  - npm run sauce-acceptance-test

