addons:
  sauce_connect: true

sudo: false
language: java

env:
  - NODE_VERSION=v6.9.2

jdk:
  - oraclejdk8

before_install:
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start

install:
  - npm i

script:
  - npm test
  - npm run coverage
  - npm run client-coverage
#  - npm run acceptance-test

