# addons:
#   sauce_connect: true

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

sudo: false
language: node_js

node_js:
  - "8.1.2"

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm i

script:
  - npm test
  - npm run coverage
  - npm run client-coverage
